export const TestRunning = 'Test.running'
export const TestPassed = 'Test.passed'
export const TestFailed = 'Test.failed'
export const AllTestsFinished = 'Test.allFinished'
export const TestsStarting = 'Tests.starting'
