export const DebuggerPaused = 'Debugger.paused'
const DebuggerResumed = 'Debugger.resumed'
const DebuggerScriptParsed = 'Debugger.scriptParsed'

const PageFrameAttached = 'Page.frameAttached'
const PageFrameDetached = 'Page.frameDetached'
const PageFrameNavigated = 'Page.frameNavigated'
const PageLifeCycleEvent = 'Page.lifecycleEvent'
const PageLoadEventFired = 'Page.loadEventFired'

const RuntimeConsoleApiCalled = 'Runtime.consoleAPICalled'
const RuntimeExecutionContextCreated = 'Runtime.executionContextCreated'
const RuntimeExecutionContextDestroyed = 'Runtime.executionContextDestroyed'
const RuntimeExecutionContextsCleared = 'Runtime.executionContextsCleared'

const TargetAttachedToTarget = 'Target.attachedToTarget'
const TargetDetachedFromTarget = 'Target.detachedFromTarget'
const TargetTargetCrashed = 'Target.targetCrashed'
const TargetTargetCreated = 'Target.targetCreated'
const TargetTargetDestroyed = 'Target.targetDestroyed'
const TargetTargetInfoChanged = 'Target.targetInfoChanged'
