export const DebuggerPaused = 'Debugger.paused'
export const DebuggerResumed = 'Debugger.resumed'
export const DebuggerScriptParsed = 'Debugger.scriptParsed'

export const PageFrameAttached = 'Page.frameAttached'
export const PageFrameDetached = 'Page.frameDetached'
export const PageFrameNavigated = 'Page.frameNavigated'
export const PageLifeCycleEvent = 'Page.lifecycleEvent'
export const PageLoadEventFired = 'Page.loadEventFired'

export const RuntimeConsoleApiCalled = 'Runtime.consoleAPICalled'
export const RuntimeExecutionContextCreated = 'Runtime.executionContextCreated'
export const RuntimeExecutionContextDestroyed = 'Runtime.executionContextDestroyed'
export const RuntimeExecutionContextsCleared = 'Runtime.executionContextsCleared'

export const TargetAttachedToTarget = 'Target.attachedToTarget'
export const TargetDetachedFromTarget = 'Target.detachedFromTarget'
export const TargetTargetCrashed = 'Target.targetCrashed'
export const TargetTargetCreated = 'Target.targetCreated'
export const TargetTargetDestroyed = 'Target.targetDestroyed'
export const TargetTargetInfoChanged = 'Target.targetInfoChanged'
