import * as IsMacos from '../IsMacos/IsMacos.js'

export const OpenQuickPickCommands = IsMacos.isMacos ? 'Meta+Shift+P' : 'Control+Shift+P'
export const OpenQuickPickFiles = IsMacos.isMacos ? 'Meta+P' : 'Control+P'
export const Escape = 'Escape'
export const F2 = 'F2'
export const ArrowDown = 'ArrowDown'
export const ArrowUp = 'ArrowUp'
export const Copy = IsMacos.isMacos ? 'Meta+C' : 'Control+C'
export const CloseTab = IsMacos.isMacos ? 'Meta+w' : 'Control+w'
