export const ConnectDevtools = 'ConnectDevtools'
export const MemoryLeakFinderCompare = 'MemoryLeakFinderCompare'
export const MemoryLeakFinderSetup = 'MemoryLeakFinderSetup'
export const MemoryLeakFinderStart = 'MemoryLeakFinderStart'
export const MemoryLeakFinderStop = 'MemoryLeakFinderStop'
export const MemoryLeakFinderStartWithWorkers = 'MemoryLeakFinderStartWithWorkers'
export const MemoryLeakFinderStopWithWorkers = 'MemoryLeakFinderStopWithWorkers'
export const MemoryLeakFinderCompareWithWorkers = 'MemoryLeakFinderCompareWithWorkers'
