export const ConnectDevtools = 'ConnectDevtools.connectDevtools'
export const MemoryLeakFinderCompare = 'MemoryLeakFinderCompare.compare'
export const MemoryLeakFinderSetup = 'MemoryLeakFinderSetup.setup'
export const MemoryLeakFinderStart = 'MemoryLeakFinderStart.start'
export const MemoryLeakFinderStop = 'MemoryLeakFinderStop.stop'
export const MemoryLeakFinderStartWithWorkers = 'MemoryLeakFinderStartWithWorkers.startWithWorkers'
export const MemoryLeakFinderStopWithWorkers = 'MemoryLeakFinderStopWithWorkers.stopWithWorkers'
export const MemoryLeakFinderCompareWithWorkers = 'MemoryLeakFinderCompareWithWorkers.compareWithWorkers'
