export const ConnectDevtools = 'ConnectDevtools.connectDevtools'
export const GetExternalRuntimeInfo = 'GetExternalRuntimeInfo.getExternalRuntimeInfo'
export const RunTest = 'RunTest.runTest'
export const SetupTest = 'Setuptest.setupTest'
export const TearDownTest = 'TearDownTest.tearDownTest'
export const Disconnect = 'Test.disconnect'
