export default {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts'],
  transform: {
    '^.+\\.ts$': [
      'ts-jest',
      {
        useESM: true,
      },
    ],
  },
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
  testMatch: ['<rootDir>/test/**/*.ts', '<rootDir>/test/**/*.js'],
  injectGlobals: false,
  collectCoverage: true,
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/index.ts',
    '!src/main.ts',
    '!src/parts/ConnectDevtools/*.ts',
    '!src/parts/DebuggerCreateIpcConnection/*.ts',
    '!src/parts/DebuggerCreateRpcConnection/*.ts',
    '!src/parts/DebuggerCreateSessionRpcConnection/*.ts',
    '!src/parts/DevtoolsProtocol/*.ts',
    '!src/parts/Ffmpeg/*.ts',
    '!src/parts/Finalize/*.ts',
    '!src/parts/FinalizeChapters/*.ts',
    '!src/parts/HandleFrame/*.ts',
    '!src/parts/IpcError/*.ts',
    '!src/parts/Logger/*.ts',
    '!src/parts/PTimeout/*.ts',
    '!src/parts/ScenarioFunctions/*.ts',
    '!src/parts/TargetState/*.ts',
    '!src/parts/VideoRecording/*.ts',
    '!src/parts/WaitForWebSocketToBeOpen/*.ts',
    '!src/parts/ErrorCodes/*.ts',
    '!src/parts/Json/*.ts',
  ],
  coverageReporters: ['text', 'lcov', 'html'],
  coverageDirectory: 'coverage',
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/test/',
    '/bin/',
  ],
}
