export const HasText = ':has-text('
export const HasExactText = ':has-exact-text('
export const Nth = ':nth('
export const InternalEnterFrame = ':internal-enter-frame('
export const EnterShadow = ':enter-shadow('
