export * as CanvasCount from '../CreateCanvasCountChart/CreateCanvasCountChart.js'
export * as DetachedDomNodeCount from '../CreateDetachedDomNodeCountChart/CreateDetachedDomNodeCountChart.js'
export * as FunctionCount from '../CreateFunctionCountChart/CreateFunctionCountChart.js'
export * as ObjectCount from '../CreateObjectCountChart/CreateObjectCountChart.js'
export * as PromiseCount from '../CreatePromiseCountChart/CreatePromiseCountChart.js'
export * as RegexCount from '../CreateRegexCountChart/CreateRegexCountChart.js'
