export const AllTestsFinished = 'Test.allFinished'
export const TestFailed = 'Test.failed'
export const TestPassed = 'Test.passed'
export const TestRunning = 'Test.running'
export const TestSkipped = 'Test.skipped'
export const TestsStarting = 'Tests.starting'
export const UnexpectedTestError = 'Test.unexpectedTestError'
