export const ConnectDevtools = 'ConnectDevtools.connectDevtools'
export const PageObjectCreate = 'PageObject.create'
export const RunTest = 'RunTest.runTest'
export const SetupTest = 'Setuptest.setupTest'
export const TearDownTest = 'TearDownTest.tearDownTest'
