export const ConnectDevtools = 'ConnectDevtools.connectDevtools'
export const ConnectElectron = 'ConnectElectron.connectElectron'
export const PageObjectCreate = 'PageObject.create'
export const RunTest = 'RunTest.runTest'
export const SetupTest = 'Setuptest.setupTest'
