import * as IsWindows from '../IsWindows/IsWindows.js'

export const ArrowDown = '\u001B[B'
export const ArrowLeft = '\u001B[D'
export const ArrowRight = '\u001B[C'
export const ArrowUp = '\u001B[A'
export const Backspace = Buffer.from(IsWindows.isWindows ? '08' : '7f', 'hex').toString()
export const ControlC = '\u0003'
export const ControlD = '\u0004'
export const ControlU = '\u0015'
export const Enter = '\r'
export const Escape = '\u001B'
export const ControlBackspace = '\u0017'
export const AltBackspace = '\u001B\u007F'
export const Home = '\u001B[H'
export const End = '\u001B[F'
