export const ArrowDown = '\u{1B}[B'
export const ArrowLeft = '\u{1B}[D'
export const ArrowRight = '\u{1B}[C'
export const ArrowUp = '\u{1B}[A'
export const Backspace = (isWindows: boolean) => Buffer.from(isWindows ? '08' : '7f', 'hex').toString()
export const ControlC = '\u{3}'
export const ControlD = '\u{4}'
export const ControlU = '\u{15}'
export const Enter = '\r'
export const Escape = '\u{1B}'
export const ControlBackspace = '\u{17}'
export const AltBackspace = '\u{1B}\u{7F}'
export const Home = '\u{1B}[H'
export const End = '\u{1B}[F'
