export const ConnectDevtools = 'ConnectDevtools.connectDevtools'
export const MemoryLeakFinderSetup = 'MemoryLeakFinderSetup.setup'
export const MemoryLeakFinderStart = 'MemoryLeakFinderStart.start'
export const MemoryLeakFinderStop = 'MemoryLeakFinderStop.stop'
export const MemoryLeakFinderCompare = 'MemoryLeakFinderStop.compare'
export const CompareNamedFunctionCount3 = 'CompareNamedFunctionCount3.compareNamedFunctionCount3'
export const WriteNodeResult = 'WriteNodeResult.writeNodeResult'
