import type { StdinDataState } from '../StdinDataState/StdinDataState.ts'
import * as Ide from '../Ide/Ide.ts'
import * as ModeType from '../ModeType/ModeType.ts'
import * as TestRunMode from '../TestRunMode/TestRunMode.ts'

export const createDefaultState = (): StdinDataState => ({
  bisect: false,
  buffering: false,
  checkLeaks: false,
  continueValue: '',
  cwd: '',
  enableExtensions: false,
  enableProxy: false,
  exitCode: 0,
  filter: '',
  headless: false,
  ide: Ide.VsCode,
  ideVersion: Ide.VsCode,
  insidersCommit: '',
  inspectExtensions: false,
  inspectExtensionsPort: 5870,
  inspectPtyHost: false,
  inspectPtyHostPort: 5877,
  inspectSharedProcess: false,
  inspectSharedProcessPort: 5879,
  isGithubActions: false,
  isWindows: false,
  measure: '',
  measureAfter: false,
  measureNode: false,
  mode: ModeType.Waiting,
  previousFilters: [],
  recordVideo: false,
  restartBetween: false,
  runMode: TestRunMode.Auto,
  runs: 1,
  runSkippedTestsAnyway: false,
  stdout: [],
  timeoutBetween: 0,
  timeouts: true,
  useProxyMock: false,
  value: '',
  watch: false,
  workers: false,
  screencastQuality: 90,
})
