export interface StartRunningOptions {
  readonly arch: string
  readonly bisect: boolean
  readonly checkLeaks: boolean
  readonly clearExtensions: boolean
  readonly color: boolean
  readonly commit: string
  readonly continueValue: string
  readonly cwd: string
  readonly enableExtensions: boolean
  readonly enableProxy: boolean
  readonly filterValue: string
  readonly headlessMode: boolean
  readonly ide: string
  readonly ideVersion: string
  readonly insidersCommit: string
  readonly inspectExtensions: boolean
  readonly inspectExtensionsPort: number
  readonly inspectPtyHost: boolean
  readonly inspectPtyHostPort: number
  readonly inspectSharedProcess: boolean
  readonly inspectSharedProcessPort: number
  readonly isGithubActions: boolean
  readonly isWindows: boolean
  readonly measure: string
  readonly measureAfter: boolean
  readonly measureNode: boolean
  readonly platform: string
  readonly recordVideo: boolean
  readonly restartBetween: boolean
  readonly runMode: number
  readonly runs: number
  readonly runSkippedTestsAnyway: boolean
  readonly screencastQuality: number
  readonly setupOnly: boolean
  readonly timeoutBetween: number
  readonly timeouts: boolean
  readonly updateUrl: string
  readonly useProxyMock: boolean
  readonly vscodePath: string
  readonly vscodeVersion: string
  readonly workers: boolean
}
