export { VSCodeFunctionTracker } from './parts/Tracker/Tracker.ts'
export { transformCode, createFunctionWrapperPlugin } from './parts/Transform/Transform.ts'
export { transformCode as transformCodeScript, createFunctionWrapperPlugin as createFunctionWrapperPluginScript } from './parts/TransformScript/TransformScript.ts'
export { createFunctionWrapperPlugin as createFunctionWrapperPluginMain } from './parts/CreateFunctionWrapperPlugin/CreateFunctionWrapperPlugin.ts'
export { trackingCode } from './parts/TrackingCode/TrackingCode.ts'
export * from './parts/Types/Types.ts'
